server:
  port: 8088
  servlet:
    context-path: /demo
spring:
  thymeleaf:
    prefix: classpath:/templates/page
    encoding: utf-8
    mode: HTML
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/templates/page

  datasource:
#    url: jdbc:mysql://144.34.169.78:3306/ych_test
#    username: ych
#    password: "!Etoak123"
    url: jdbc:mysql://localhost/test
    username: root
    password: "etoak"
#    driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: com.mysql.jdbc.Driver

#mq
  application:
    name: spirng-boot-rabbitmq
  rabbitmq:
    host: 127.0.0.1
    #host: 144.34.169.78
    port: 5672
    #username: guest
    username: guest
    password: guest

## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mapping/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.example.demo.mapper  # 注意：对应实体类的路径





